// <auto-generated />
using System;
using AISSmartFactory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AISSmartFactory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260927155031_FixDowntimeReasonColumns")]
    partial class FixDowntimeReasonColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("AISSmartFactory.Models.Maintenance.MaintenanceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MachineRunningHours")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCause")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SparePartsUsed")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Technician")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("NextDueDate");

                    b.HasIndex("StartTime");

                    b.ToTable("MaintenanceRecords", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.CncProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GlassTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Revision")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetCycleTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlassTypeId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProgramNumber", "Revision");

                    b.ToTable("CncPrograms", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.DefectType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DefectTypes", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.DowntimeReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresComment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReasonCode")
                        .IsUnique();

                    b.ToTable("DowntimeReasons", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.GlassType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoatingType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlassCategory")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlassName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Length")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Thickness")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Width")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlassCode")
                        .IsUnique();

                    b.ToTable("GlassTypes", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.Machine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommunicationProtocol")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCommunicationAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IPAddress");

                    b.HasIndex("MachineCode")
                        .IsUnique();

                    b.ToTable("Machines", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.Operator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shift")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Operators", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.Tool", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentLife")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Diameter")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedLife")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Length")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("LifeUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumRpm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specification")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolCode")
                        .IsUnique();

                    b.ToTable("Tools", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.CncProcessData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AirPressure")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoolantFlow")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoolantPressure")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoolantTemperature")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CuttingDepth")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CycleTimeSeconds")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FeedRate")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MachineTemperature")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MotorCurrent")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SpindleLoad")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpindleRpm")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VacuumPressure")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Vibration")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("XPosition")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("YPosition")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ZPosition")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionRunId");

                    b.HasIndex("Timestamp");

                    b.ToTable("CncProcessData", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.CncProductionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AirPressure")
                        .HasColumnType("TEXT");

                    b.Property<long>("CncProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CoolantPressure")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CuttingDepth")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CycleTimeSeconds")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EnergyKwh")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FeedRate")
                        .HasColumnType("TEXT");

                    b.Property<long>("GlassTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoodQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MachineLoadPercent")
                        .HasColumnType("TEXT");

                    b.Property<long>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("QualityApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualityRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RejectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpindleRpm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ToolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CncProductionEntries");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.MachineAlarm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DurationSeconds")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("StartTime");

                    b.ToTable("MachineAlarms", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.MachineDowntime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DowntimeReasonId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DurationMinutes")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeReasonId");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("StartTime");

                    b.ToTable("MachineDowntime", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.MachineTelemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StringValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "Timestamp");

                    b.HasIndex("MachineId", "TagName", "Timestamp");

                    b.ToTable("MachineTelemetry", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.ProductionOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CncProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawingRevision")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("GlassTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoodQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RejectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CncProgramId");

                    b.HasIndex("GlassTypeId");

                    b.HasIndex("MachineId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("ProductionOrders", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.ProductionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CycleTimeSeconds")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGood")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PieceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("StartTime");

                    b.ToTable("ProductionRuns", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Quality.QualityDefect", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DefectTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefectTypeId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("ProductionRunId");

                    b.ToTable("QualityDefects", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Quality.QualityInspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionPhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectorName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionTime");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductionRunId");

                    b.ToTable("QualityInspections", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Quality.QualityMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Deviation")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LowerLimit")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasuringInstrument")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("QualityInspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpecificationNominal")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UpperLimit")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QualityInspectionId");

                    b.ToTable("QualityMeasurements", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Tooling.ToolUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProductionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RemainingLifeHours")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemainingLifePieces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ToolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UsageHours")
                        .HasPrecision(12, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionRunId");

                    b.HasIndex("StartTime");

                    b.HasIndex("ToolId");

                    b.ToTable("ToolUsages", (string)null);
                });

            modelBuilder.Entity("AISSmartFactory.Models.Maintenance.MaintenanceRecord", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Master.CncProgram", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.GlassType", "GlassType")
                        .WithMany()
                        .HasForeignKey("GlassTypeId");

                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GlassType");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.CncProcessData", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISSmartFactory.Models.Production.ProductionRun", "ProductionRun")
                        .WithMany()
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.MachineAlarm", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.MachineDowntime", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.DowntimeReason", "DowntimeReason")
                        .WithMany()
                        .HasForeignKey("DowntimeReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISSmartFactory.Models.Master.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DowntimeReason");

                    b.Navigation("Machine");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.ProductionOrder", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.CncProgram", "CncProgram")
                        .WithMany()
                        .HasForeignKey("CncProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AISSmartFactory.Models.Master.GlassType", "GlassType")
                        .WithMany()
                        .HasForeignKey("GlassTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CncProgram");

                    b.Navigation("GlassType");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Production.ProductionRun", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISSmartFactory.Models.Master.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AISSmartFactory.Models.Production.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operator");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Quality.QualityDefect", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.DefectType", "DefectType")
                        .WithMany()
                        .HasForeignKey("DefectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISSmartFactory.Models.Production.ProductionRun", "ProductionRun")
                        .WithMany()
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectType");

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Quality.QualityInspection", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AISSmartFactory.Models.Production.ProductionRun", "ProductionRun")
                        .WithMany()
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Quality.QualityMeasurement", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Quality.QualityInspection", "QualityInspection")
                        .WithMany()
                        .HasForeignKey("QualityInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QualityInspection");
                });

            modelBuilder.Entity("AISSmartFactory.Models.Tooling.ToolUsage", b =>
                {
                    b.HasOne("AISSmartFactory.Models.Master.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISSmartFactory.Models.Production.ProductionRun", "ProductionRun")
                        .WithMany()
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AISSmartFactory.Models.Master.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("ProductionRun");

                    b.Navigation("Tool");
                });
#pragma warning restore 612, 618
        }
    }
}
